tech_mart/cartapp/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('',views.cart_view,name='view_cart'),
    path('add/<str:slug>/',views.add_cart,name='add_cart'),
    path('remove/<str:slug>/',views.remove_item,name='remove_from_cart'),
    path('remove_all/<str:slug>/',views.remove_all_item,name='remove_all_from_cart'),
    path('add_to_wishlist/<str:slug>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<str:slug>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('wishlist/',views.whishlist,name='wishlist'),
    path('remove_coupon/',views.remove_coupon,name='remove_coupon'),



]

tech_mart/orders/urls.py
from django.urls import path
from. import views
app_name = 'orders'
urlpatterns = [
  
    path('place_order/',views.checkout,name='place_order'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel'),
    path('order_details/<int:id>',views.order_details,name='order_details'),
    path('payment_success/<str:id>',views.payment_success,name='payment_success'),
    path('payment_failed/<str:id>',views.payment_failed,name='payment_failed'),
    path('return_order/<int:id>',views.return_order,name='return_order'),
    path('wallet/',views.view_wallet,name='wallet'),
    path('chage_payment/<int:order_id>',views.change_payment_method,name='change_payment_method'),
  
  
    
]

tech_mart/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("product/<str:slug>", views.ProductDetail.as_view(), name="detail"),
    path("category1/", views.ShopList.as_view(), name="shop"),
    path('category/', views.allProdCat, name='allProdCat-old'),
    path('category/<slug:c_slug>/', views.allProdCat, name='by_category'),
    path('filter/', views.filter_product_list, name='allProdCat'),
     path('review/<int:pk>/edit/', views.edit_review, name='edit_review'),
]

tech_mart/tech_mart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("shop.urls")),
    path("accounts/",include("customer.urls")),
    path("cadmin/",include("adminUser.urls")),
    path("cart/",include("cartapp.urls")),
    path("orders/",include("orders.urls")),
    path("reset",include("passwordreset.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_mart/cartapp/models.py
from django.db import models
from shop.models import Product
from customer.models import Customer
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.core.validators import MinLengthValidator,MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from shop.models import validate_non_empty
def validate_valid_dates(value):
    if value.valid_from >= value.valid_to:
        raise ValidationError({'valid_from': ('Valid from date must be earlier than valid to date.')})

# Create your models here.
class Coupons(models.Model):
    coupon_code = models.CharField(max_length=100, unique=True, validators=[MinLengthValidator(5, "Coupon code must be at least 5 characters"),validate_non_empty],)
    description = models.TextField(validators = [MinLengthValidator(5, "Description must be at least 5 characters"),validate_non_empty])
    minimum_amount = models.IntegerField(default=100)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    is_expired = models.BooleanField(default=False)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def clean(self):
        validate_valid_dates(self)

    def __str__(self):
        return self.coupon_code

    def is_valid(self):
        now = timezone.now()
        if self.valid_to != now:
            self.is_expired = True
            return self.is_expired
        else:
            return self.is_expired

    def is_used_by_user(self, user):
        redeemed_details = UserCoupons.objects.filter(
            coupon=self, user=user, is_used=True
        )
        return redeemed_details.exists()
    class Meta:
        ordering = ("-updated",)
        verbose_name = 'coupon'
        verbose_name_plural = 'coupons'

class UserCoupons(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    coupon = models.ForeignKey(
        Coupons, on_delete=models.CASCADE, related_name="redeemed_by"
    )

    is_used = models.BooleanField(default=False)

    def __str__(self):
        return self.coupon.coupon_code


class Wishlist(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Cart(models.Model):

    user = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="carts")
    date_added = models.DateField(auto_now_add=True)
    coupon = models.ForeignKey(
        Coupons,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default="",
        related_name="carts",
    )

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for cart_item in self.cart_items.all():
            total += cart_item.total()

        return round(total, 2)

    def get_total_discount(self):
        total = 0
        for cart_item in self.cart_items.all():
            if cart_item.product.price_after_discount():
                total += cart_item.product.price_after_discount()
                
        print(f"{total} discount")
        return round(total, 2)

    def coupon_is_valid(self):
        if not self.coupon:
            print("No coupon applied.")
            return False
    
        if self.get_subtotal() < self.coupon.minimum_amount:
            print("Coupon minimum amount requirement not met.")
            return False
    
        if self.coupon.is_expired:
            print("Coupon is expired.")
            return False
    
        if self.coupon.valid_to < timezone.now():
            print("Coupon validity period has ended.")
            return False
    
        print("Coupon is valid.")
        return True

    def total_after_coupon(self):
        if self.coupon_is_valid():
            return round(self.get_total() - self.get_total() * self.coupon.discount / 100,2)
        else:
            return self.get_total()

    def get_subtotal(self):
        subtotal = 0
        for cart_item in self.cart_items.all():
            subtotal += cart_item.sub_total()
        return subtotal

    def is_already_used(self):
        if self.coupon.is_used_by_user(self.user):
            return True
        else:
            return False


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True
    )
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    def total(self):
        if self.product.discount or self.product.category.category_discount:
           
            total = self.product.price_after_discount() * self.quantity 
        
        else:
         
            total = self.product.price * self.quantity
        return round(total, 2)

    def check_quantity(self):
        if self.quantity > self.product.stock:
            return False
        return True

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

    def sub_total(self):
        return self.product.price * self.quantity

tech_mart/cartapp/forms.py
from django import forms
from .models import Coupons
class CouponApplyForm(forms.Form):
    code = forms.CharField(label='Coupon Code')

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupons
        fields = ['coupon_code', 'description','minimum_amount', 'discount', 'is_expired', 'valid_from', 'valid_to']
        widgets = {
          
            
            'valid_from': forms.DateTimeInput(attrs={'class': 'form-control','type':'datetime-local'},),
            'valid_to': forms.DateTimeInput(attrs={'class': 'form-control','type':'datetime-local'},),
        }

tech_mart/cartapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Product
from customer.models import Customer
from .models import Cart,CartItem, Coupons, UserCoupons, Wishlist
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from orders.models import Order, OrderItem
from customer.forms import AddressForm
from.forms import CouponApplyForm
from django.utils import timezone
# Create your views here.


@login_required
def add_cart(request, slug):
    product=Product.objects.get(slug=slug)
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user)
    cart.save()
    cart_items=CartItem.objects.filter(cart=cart,product=product).first()
    if cart_items:
        if cart_items.quantity < product.stock:
            cart_items.quantity+=1
            cart_items.save()
        else:
            messages.error(request, "Product is out of stock")
        
        
    else:
        cart_items=CartItem.objects.create(cart=cart,product=product,quantity=1)
        cart_items.save()
    return redirect('cart:view_cart')
@login_required
def remove_item(request, slug):
    product=Product.objects.get(slug=slug)
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user)
    cart_items=CartItem.objects.filter(cart=cart,product=product).first()
    if cart_items:
        if cart_items.quantity > 1:
            cart_items.quantity -= 1
            cart_items.save()
        else:
            cart_items.delete()
    return redirect('cart:view_cart') 

@login_required
def remove_all_item(request, slug):
    product=Product.objects.get(slug=slug)
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user)
    cart_items=CartItem.objects.filter(cart=cart,product=product).first()
    if cart_items:
        cart_items.delete()
    return redirect('cart:view_cart')    
@login_required
def cart_view(request):
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user)
    print(cart)
    cart_items=CartItem.objects.filter(cart=cart)
    form = CouponApplyForm()
    if request.method == 'POST':
        form = CouponApplyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            try:
                coupon = Coupons.objects.get(coupon_code__iexact=code, is_expired=False)
            except Coupons.DoesNotExist:
                messages.error(request, 'Invalid coupon code')
            else:
                if coupon.is_used_by_user(request.user):
                    messages.error(request, 'You have already used this coupon')
                elif cart.get_subtotal() < coupon.minimum_amount:
                    messages.error(request, f'Minimum order value for this coupon is {coupon.minimum_amount}')
                elif coupon.valid_to < timezone.now():
                    messages.error(request, 'Coupon is expired')
                else:
                    cart.coupon = coupon
                    cart.save()
                    
                    messages.success(request, 'Coupon applied successfully')
    
    context={
        'cart_items':cart_items,
        'cart':cart,
        'form':form
    }
    return render(request,'cartapp/cart.html',context)

def remove_coupon(request):
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user)
    cart.coupon=None
    cart.save()
    messages.success(request, 'Coupon removed successfully')
    return redirect('cart:view_cart')
@login_required
def add_to_wishlist(request, slug):
    product=Product.objects.get(slug=slug)
    user = request.user
    wishlist_item, created = Wishlist.objects.get_or_create(user=user, product=product)

    if created:
        # Item added to wishlist
        pass
    else:
        # Item already in wishlist
        pass

    
    
    return redirect('shop:detail',slug=slug)
   
@login_required
def remove_from_wishlist(request, slug):
    product=Product.objects.get(slug=slug)
    user=request.user
    whishlist_item=Wishlist.objects.filter(user=user,product=product).first()
    whishlist_item.delete()
    return redirect('shop:detail',slug=slug)
@login_required
def whishlist(request):
    user=request.user
    whishlist_items=Wishlist.objects.filter(user=user)
    products=Product.objects.filter(wishlist__in=whishlist_items)
    #filtering out items already in cart
    cart = Cart.objects.get(user=user)
    cart_items = CartItem.objects.filter(cart=cart)
    product_ids_in_cart = cart_items.values_list('product_id', flat=True)
    products = products.exclude(id__in=product_ids_in_cart)
    print(products)
    for product in products:
        print(product.name)
    print(whishlist_items)
    
    context={
        'products':products
    }
    return render(request,'cartapp/wishlist.html',context)

tech_mart/cartapp/templates/cartapp/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is Cart Page. proceed to review items and place order
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your cart is empty</h1>
        <br>
        <p class="text-center">Please click <a href="{% url 'shop:home' %}"> here </a> to continue shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping Cart</h1>
        <br>
    </div>
</div>
<div class="container-fluid">
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table ">
                <thead>
                    <tr>
                        <th class="my_custom_thead rounded-top" colspan="5">Your Items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="{{cart_item.product.get_url}}"><img
                                    src="{{cart_item.product.images.first.image.url}}" alt=""
                                    class="float-left rounded custom_image" height="125px" width="125px"></a>
                        </td>
                        <td class="text-left">
                            {{cart_item.product.name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            {% if cart_item.product.discount < cart_item.product.price %}
                            <p class="fs-poppins bold-500">$ <span class="text-decoration-line-through">
                                    {{cart_item.product.price}} </span> {{cart_item.product.price_after_discount}} </p>
                            {% else %}
                            PRICE:$ {{cart_item.product.price}}
                            {% endif %}
                            <br>
                            Quantity:{{cart_item.quantity}}
                        </td>
                        <td>
                            $ {{cart_item.total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %} <td class="flex">
                            <a href="{% url 'cart:add_cart' cart_item.product.slug %}" class="custom_a"> <i
                                    class="fa-solid fa-plus custom_icon"></i></a>

                            <a href="{% url 'cart:remove_from_cart' cart_item.product.slug %}" class="custom_a"><i
                                    class="fa-solid fa-minus custom_icon"></i></a>
                            <a href="{% url 'cart:remove_all_from_cart' cart_item.product.slug %}" class="custom_a"><i
                                    class="fa-solid fa-trash custom_icon"></i></a>
                            </td>
                            {% else %}
                            <td class="flex">
                                &nbsp;
                                <a href="{% url 'cart:remove_from_cart' cart_item.product.slug %}" class="custom_a"><i
                                        class="fa-solid fa-minus custom_icon"></i></a>
                                <a href="{% url 'cart:remove_all_from_cart' cart_item.product.slug %}"
                                    class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                            </td>
                            {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div class="mx-auto">
                <table class="table my_custom_table">
                    <thead>
                        <tr>
                            <th class="my_custom_thead rounded-top">
                                Check Out
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart items before proceeding with order payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                {% if cart.total_after_coupon != cart.get_total%}
                                Your Total : <span class="text-decoration-line-through">${{cart.get_total}}</span>
                                <strong>${{cart.total_after_coupon}}</strong>
                                <br>
                                <p>'{{cart.coupon}}' Coupon applied </p>
                                <p>You got {{cart.coupon.discount}}% off</p>
                                {% else %}
                                Your Total :<strong>${{cart.get_total}} </strong>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left"></td>
                        </tr>
                        <tr>
                            <td>
                                <a href="{% url 'shop:home' %}"
                                    class="btn btn-secondary btn-block my_custom_button">continue shopping</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-1">Apply Coupon</button>
        </form>
        <a href="{% url 'cart:remove_coupon' %}"><button type="submit" class="btn btn-danger mt-1">Remove
                Coupon</button></a>
        <a href="{% url 'orders:place_order' %}" class="btn btn-secondary btn-block my_custom_button mt-1">Check
            out</a>
    </div>
</div>
{% endif %}
{% endblock %}

tech_mart/cartapp/templates/cartapp/wishlist.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/shop.css' %}" />
 <link rel="stylesheet" href="{% static 'css/product.css' %}" />
<script src="{% static 'js/shop.js' %}" defer></script>
{% endblock css %}
{% block content %}
<section class="shop-feature bg-gray grid">
   <h2 class="fs-montserrat fs-300 bold-700">You Whishlist</h2>
    
  </section>
<section class="shop-product grid container">
    {% for product in products %}
     <div class="product-list grid">
       <img src="{{product.images.first.image.url}}" alt=""  style="max-width: 20vw;"/>
       <p class="fs-montserrat bold-600">{{product.name}}</p>
       <div class="shop-btn flex">
         <button class="bg-red text-white fs-montserrat "><a class="text-white" href="{% url 'shop:detail' product.slug %}">Add To Cart</a>
         </button>
         {% if product.price_after_discount < product.price %}
        
        <p class="fs-poppins bold-500">$ <span class="text-decoration-line-through"> {{product.price}} </span> {{product.price_after_discount}} </p>

        {% else %}
        
        <p class="fs-poppins bold-500">${{product.price}}</p>
            {% endif %}
            <a href="{% url 'cart:remove_from_wishlist' product.slug %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
       </div>

       <!-- ===============Pop-Up========================== -->

       <div class="pup-up">
           <p class="fs-poppins">{{product.label}}</p>
       </div>

       
       <!-- ===============Pop-Up========================== -->

     </div>
     {% empty %}
     <div>
     <h2 class="fs-montserrat fs-300 bold-700">No Products</h2>
     <p class="fs-poppins">You have no products in your wishlist</p>
      <button class="bg-red text-white fs-montserrat "><a class="text-white" href="{% url 'shop:home' %}">Continue Shopping</a>
      </div>
        {% endfor %}
   
    
   </section>


  
{% endblock content %}