tech_mart/customer/urls.py
from django.urls import path
from . import views
#imports for forgotten password
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name='customer'
urlpatterns=[
    path('',views.registerView,name='register'),
    path('otp/<int:id>', views.verifyOtp, name='otp'),
    path("resend_otp/<int:id>",views.resendOtp,name='resend_otp'),    
    path("login/",views.login_view,name='login'),
    path("logout/",views.logout_view,name='logout'),
    path("profile/",views.profile_view,name='profile'),
    path("change_password/",views.change_password_view,name='change_password'),
    path("edit_profile/",views.edit_profile_view,name='edit_profile'),
    path("add_new_address/<str:source>",views.add_new_address,name='add_new_address'),
    path("edit_address/<int:id>",views.edit_address,name='edit_address'),
    path("delete_address/<int:id>",views.delete_address,name='delete_address'),
    path("check_username/",views.check_username,name='check_username'),
    path('validate_password/',views.validate_passwords_view,name='validate_passwords'),
    path('test_register/',views.test_register,name='test_register'),
    path('create_referral_link/',views.create_referral_link,name='create_referral_link'),
    

]

tech_mart/orders/urls.py
from django.urls import path
from. import views
app_name = 'orders'
urlpatterns = [
  
    path('place_order/',views.checkout,name='place_order'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel'),
    path('order_details/<int:id>',views.order_details,name='order_details'),
    path('payment_success/<str:id>',views.payment_success,name='payment_success'),
    path('payment_failed/<str:id>',views.payment_failed,name='payment_failed'),
    path('return_order/<int:id>',views.return_order,name='return_order'),
    path('wallet/',views.view_wallet,name='wallet'),
    path('chage_payment/<int:order_id>',views.change_payment_method,name='change_payment_method'),
  
  
    
]

tech_mart/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("product/<str:slug>", views.ProductDetail.as_view(), name="detail"),
    path("category1/", views.ShopList.as_view(), name="shop"),
    path('category/', views.allProdCat, name='allProdCat-old'),
    path('category/<slug:c_slug>/', views.allProdCat, name='by_category'),
    path('filter/', views.filter_product_list, name='allProdCat'),
     path('review/<int:pk>/edit/', views.edit_review, name='edit_review'),
]

tech_mart/tech_mart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("shop.urls")),
    path("accounts/",include("customer.urls")),
    path("cadmin/",include("adminUser.urls")),
    path("cart/",include("cartapp.urls")),
    path("orders/",include("orders.urls")),
    path("reset",include("passwordreset.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_mart/customer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator,MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
# Created Customer 
def validate_non_empty(value):
    if value.strip() == '':
        raise ValidationError("This field cannot be empty.")
class Address(models.Model):
    user = models.ForeignKey(
        'Customer',
        on_delete=models.CASCADE,
        related_name='addresses',
        blank=True,
        null=True)
    street_address = models.CharField(max_length=255 ,validators=[MinLengthValidator(10, "Street address must be at least 10 characters"),validate_non_empty])
    city = models.CharField(max_length=100,validators=[MinLengthValidator(5, "City must be at least 5 characters"),validate_non_empty])
    state = models.CharField(max_length=100,validators=[MinLengthValidator(5, "State must be at least 5 characters"),validate_non_empty])
    zip_code = models.CharField(max_length=20,validators=[MinLengthValidator(5, "Zip code must be at least 5 characters"),validate_non_empty])
    default_address = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.state} {self.zip_code}"
    
   
    
class Customer(AbstractUser):
    phone_number=models.CharField(max_length=15)
    address=models.ForeignKey(Address, on_delete=models.SET_NULL, related_name='customers',blank=True,null=True)
    otp=models.CharField(max_length=100,null=True,blank=True)
    is_verified=models.BooleanField(default=False)
    referral_code = models.CharField(max_length=10, unique=True,null=True,blank=True)


class Wallet(models.Model):
    balance=models.DecimalField(max_digits=100,decimal_places=2,default=0)
    customer=models.OneToOneField(Customer,on_delete=models.CASCADE,related_name='wallet')

    def __str__(self):
        return f"{self.customer.username}'s Wallet"
    

tech_mart/customer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import Customer,Address

# Customer registration form

class CustomerRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "username",
            "is_verified",
        )
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username.strip()) < 4:
            raise forms.ValidationError("Username must have at least 4 characters.")
        return username

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = (
            "street_address",
            "city",
            "state",
            "zip_code",
           
        )
        widgets = {
            "street_address": forms.TextInput(),
            "city": forms.TextInput(),
            "state": forms.TextInput(),
            "zip_code": forms.TextInput(),
           
        }

class CuatomerEditForm(UserChangeForm):
    password = None
    class Meta:
        
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "username",
           
        )
        widgets = {
            "email": forms.EmailInput(),
            "phone_number": forms.NumberInput(),
            "username": forms.TextInput(),
            "first_name": forms.TextInput(),
            "last_name": forms.TextInput(),
           
        }
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username.strip()) < 4:
            raise forms.ValidationError("Username must have at least 4 characters.")
        return username

class AddressSelectForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields=("address",)
        widgets = {
            "address": forms.Select(attrs={"class":"form-control "}),
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(AddressSelectForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['address'].queryset = Address.objects.filter(user=user)

tech_mart/customer/views.py
import re
import random
import string
from django.forms import ValidationError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Customer, Address, Wallet
from .forms import CustomerRegistrationForm
import random
from .helper import MessageHandler
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from orders.models import Order, OrderItem
from cartapp.models import Cart, CartItem
from customer.forms import AddressForm, CuatomerEditForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, update_session_auth_hash
import secrets
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST


def generate_otp(length=6):
    """
    Generate a random OTP of the specified length.

    Parameters:
    - length: Length of the OTP (default is 6).

    Returns:
    A string representing the generated OTP.
    """
    otp = "".join(secrets.choice("0123456789") for _ in range(length))
    return otp


# Create your views here.


def registerView(request):
    form = CustomerRegistrationForm()

    if request.method == "POST":
        form = CustomerRegistrationForm(request.POST)

        if form.is_valid():
            messages.success(request, "Registration successful!")
            otp = generate_otp()

            customer = form.save(commit=False)
            customer.otp = otp
            customer.save()
            referral_code = request.GET.get('referral_code')
            if referral_code:
               referrer = get_object_or_404(Customer, referral_code=referral_code)
               try:
                   referrer_wallet = Wallet.objects.get(customer=referrer)
                   print("Referrer wallet balance: ", referrer_wallet.balance)
                   referrer_wallet.balance += 100
                   referrer_wallet.save()
                   print("Referrer wallet balance: ", referrer_wallet.balance)
                   print("refferer: ", referrer.username)
               except Wallet.DoesNotExist:
                   referrer_wallet = Wallet.objects.create(customer=referrer, balance=100)
                   print("Referrer wallet balance: ", referrer_wallet.balance)
               
                

            red = redirect("customer:otp", customer.id)
            red.set_cookie("can_otp_enter", True, max_age=600)
            return red

        else:
            print(form.errors)
            messages.error(request, form.errors)

    return render(request, "customer/register.html", {"form": form})


def verifyOtp(request, id):

    if request.method == "POST":
        profile = Customer.objects.get(id=id)
        if request.COOKIES.get("can_otp_enter") is not None:
            if profile.otp == request.POST["otp"]:
                profile.is_verified = True
                profile.save(update_fields=["is_verified"])
                login(request, profile)
                red = redirect("shop:home")
                red.set_cookie("verified", True)
                return red
            messages.error(request, "Wrong OTP")
            return render(request, "customer/verify_otp.html", {"id": id})
        messages.error(request, "Wrong OTP")
        return render(request, "customer/verify_otp.html", {"id": id})
    return render(request, "customer/verify_otp.html", {"id": id})


def resendOtp(request, id):
    profile = Customer.objects.get(id=id)
    otp = generate_otp()
    profile.otp = otp
    profile.save(update_fields=["otp"])
    messages.success(request, "OTP resent")
    print(f"Generated OTP: {otp}")
    print(profile.id)
    red = redirect("customer:otp", profile.id)
    red.set_cookie("can_otp_enter", True, max_age=600)
    return red


def logout_view(request):
    logout(request)
    return redirect("shop:home")


def login_view(request):
    if request.user.is_authenticated:
        return redirect("shop:home")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Hello {username}")
            return redirect("shop:home")
        else:
            messages.error(request, "Invalid credentials")
            return redirect("customer:login")

    return render(request, "customer/login.html")


@login_required
def profile_view(request):
    if request.user.is_authenticated:
        customer = Customer.objects.get(username=request.user.username)
        customer_addresses = Address.objects.filter(user=request.user)
        orders_list = Order.objects.filter(
            customer=customer, is_returned=False
        ).order_by("-date_ordered")
        paginator = Paginator(orders_list, 10)  # Show 10 orders per page

        page = request.GET.get("page")
        try:
            orders = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            orders = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            orders = paginator.page(paginator.num_pages)

        order_count = orders_list.count()
        total_orders = sum(order.total_price for order in orders_list)

        return render(
            request,
            "customer/profile.html",
            {
                "customer": customer,
                "orders": orders,
                "order_count": order_count,
                "total_orders": total_orders,
                "customer_addresses": customer_addresses,
            },
        )


@login_required
def add_new_address(request,source):
    form = AddressForm()
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            messages.success(request, "Address added successfully!")
            if source == "profile":
                return redirect("customer:profile")
            elif source == "checkout":
                return redirect("orders:place_order")
            return redirect("customer:profile")
        else:
            messages.error(request, form.errors)
            return redirect("customer:profile")

    return render(request, "customer/add_new_address.html", {"form": form})


@login_required
def edit_address(request, id):
    address = Address.objects.get(id=id)
    form = AddressForm(instance=address)
    if request.method == "POST":
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            messages.success(request, "Address updated successfully!")
            return redirect("customer:profile")
        messages.error(request, form.errors)
    return render(request, "customer/edit_address.html", {"form": form})


@login_required
def delete_address(request, id):
    address = Address.objects.get(id=id)
    print(address)
    address.delete()
    messages.success(request, "Address deleted successfully!")
    return redirect("customer:profile")


from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError as DjangoValidationError


@login_required
def change_password_view(request):
    if request.method == "POST":
        current_password = request.POST.get("current_password")
        new_password = request.POST.get("password1")
        confirm_password = request.POST.get("password2")

        try:
            # Validate the new password using Django's built-in password validators
            validate_password(new_password, request.user)

            # Check if new password matches the confirm password
            if new_password == confirm_password:
                # Authenticate user with current password
                user = authenticate(
                    username=request.user.username, password=current_password
                )
                if user is not None:
                    # Set new password and save user
                    user.set_password(new_password)
                    user.save()
                    # Update session auth hash to keep user logged in after password change
                    update_session_auth_hash(request, user)
                    messages.success(request, "Password changed successfully!")
                    return redirect("customer:profile")
                else:
                    messages.error(request, "Invalid credentials")
            else:
                messages.error(request, "Passwords do not match")
        except DjangoValidationError as e:
            # If new password validation fails, display error messages to the user
            for error in e.messages:
                messages.error(request, error)

        # If there's any error, or passwords don't match, redirect back to the change password page
        return redirect("customer:change_password")
    else:
        return render(request, "customer/change_password.html")


@login_required
def edit_profile_view(request):
    if request.method == "POST":
        form = CuatomerEditForm(request.POST, instance=request.user)
        form_address = AddressForm(request.POST, instance=request.user.address)

        if form.is_valid() and form_address.is_valid():
            form.save()

            address = form_address.save(commit=False)
            address.user = request.user
            address.save()

            messages.success(request, "Profile updated successfully!")
            return redirect("customer:profile")
        else:
            messages.error(request, form_address.errors)

tech_mart/customer/templates/customer/change_password.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href='{% static "css/form.css" %}' />
{% endblock css %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Change Password</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-row">
          <div class="input-data">
            <input type="password" name="current_password" required />
            <div class="underline"></div>
            <label for="current_password">Current Password</label>
          </div>
        </div>
        <div class="form-row">
          <div class="input-data">
              <input type="password" name="password1" id="password1" required hx-post="{% url 'customer:validate_passwords' %}" hx-target="#passwordValidationResult" hx-trigger="keyup"/>
              <div class="underline"></div>
              <label for="password1">Password</label>
          </div>
          <div class="input-data">
              <input type="password" name="password2" id="password2" required hx-post="{% url 'customer:validate_passwords' %}" hx-target="#passwordValidationResult" hx-trigger="keyup"/>
              <div class="underline"></div>
              <label for="password2">Confirm Password</label>
          </div>
        </div>
        <div id="passwordValidationResult"></div>
        <input type="submit" class="btn btn-success" value="Change Password" />
       
      </form>
    </div>
  </div>
</div>

{% endblock content %}

tech_mart/customer/templates/customer/check_username.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href='{% static "css/form.css" %}' />
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<script defer src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="">
    <div class="">
      <h2>Register Now</h2>
      <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-row">
          <div class="input-data">
            <input type="text" name="{{ form.first_name.name }}" required />
            <div class="underline"></div>
            <label for="{{ form.first_name.name }}">First Name</label>
            {% if form.first_name.errors %}
            <div class="error">
              {{ form.first_name.errors }}
              
            </div>
            {% endif %}
          </div>
          <div class="input-data">
            <input type="text" name="{{ form.last_name.name }}" required />
            <div class="underline"></div>
            <label for="{{ form.last_name.name }}">Last Name</label>
            {% if form.last_name.errors %}
            <div class="error">
              {{ form.last_name.errors }}
             
            </div>
            {% endif %}
          </div>
        </div>
        <div class="form-row">
          <div class="input-data">
            <input type="text" name="{{ form.email.name }}" required />
            <div class="underline"></div>
            <label for="{{ form.email.name }}">Email</label>
            {% if form.email.errors %}
            <div class="error">
              {{ form.email.errors }}
              
            </div>
            {% endif %}
          </div>
          <div class="input-data">
            <input type="text" name="{{ form.phone_number.name }}" required />
            <div class="underline"></div>
            <label for="{{ form.phone_number.name }}">Phone Number</label>
            {% if form.phone_number.errors %}
            <div class="error">
              {{ form.phone_number.errors }}
              
            </div>
            {% endif %}
          </div>
        </div>

        <div class="form-row">
          <div class="input-data">
            <input type="text" name="{{ form.username.name }}" required hx-post="{% url 'customer:check_username' %}" hx-target="#username_result"   hx-trigger="input change delay:1000ms" autocomplete="off" />
            
            <div class="underline"></div>
            <label for="{{ form.username.name }}">Username</label>
            <div id="username_result"></div>
            {% if form.username.errors %}
            <div class="error">
              {{ form.username.errors }}
              
            </div>
            {% endif %}
          </div>
        </div>

        <div class="form-row">
          <div class="input-data">
              <input type="password" name="{{ form.password1.name }}" id="password1" required hx-post="{% url 'customer:validate_passwords' %}" hx-target="#passwordValidationResult" hx-trigger="keyup"/>
              <div class="underline"></div>
              <label for="{{ form.password1.name }}">Password</label>
              {% if form.password1.errors %}
              <div class="error">
                {{ form.password1.errors }}
                
              </div>
              {% endif %}
          </div>
          <div class="input-data">
              <input type="password" name="{{ form.password2.name }}" id="password2" required hx-post="{% url 'customer:validate_passwords' %}" hx-target="#passwordValidationResult" hx-trigger="keyup"/>
              <div class="underline"></div>
              <label for="{{ form.password2.name }}">Confirm Password</label>
              {% if form.password2.errors %}
              <div class="error">
                {{ form.password2.errors }}
                
              </div>
              {% endif %}
          </div>
        </div>
        <div id="passwordValidationResult"></div>

        <button type="submit" class="bg-green large-btn text-white mt-2">
          Verify
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

tech_mart/customer/templates/customer/homew.html
{% extends "base.html" %}

{% block content %}
{% for i in users %}
{{i.email}}
<br>
{% endfor %}
{% endblock content %}

tech_mart/customer/templates/customer/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/shop.css' %}" />
<link rel="stylesheet" href="{% static 'css/product.css' %}" />
<script src="{% static 'js/shop.js' %}" defer></script>

{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center fs-montserrat">PROFILE</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><span class="fs-montserrat bold-600">Username:</span></td>
            <td>{{ user.username }}</td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">Email:</span></td>
            <td>{{ user.email }}</td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">First Name:</span></td>
            <td>{{ user.first_name }}</td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">Last Name:</span></td>
            <td>{{ user.last_name }}</td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">Total Orders:</span></td>
            <td>{{ order_count }}</td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">generate refferal link:</span></td>
            <td id="link_target"><a href="" hx-get="{% url 'customer:create_referral_link' %}"  hx-target="#link_target" class="btn btn-primary">Generate</a></td>
          </tr>
          <tr>
            <td><span class="fs-montserrat bold-600">Customer addresses</span></td>
            <td>
              {% for address in customer_addresses %}
              {{ address }}
              <div class="float-right">
                <a href="{% url 'customer:edit_address' address.id %}" class="btn btn-warning"><i
                    class="fa-solid fa-pen-to-square"></i> </a>

                <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                  data-bs-target="#staticBackdrop{{ address.id }}">
                  <a><i class="fa-solid fa-trash-can"></i> </a>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop{{ address.id }}" data-bs-backdrop="static"
                  data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">ARE YOU SURE YOU WANT TO DELETE?</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        {{ address }}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger"><a
                            href="{% url 'customer:delete_address' address.id %}" class="text-white">YES </a>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr>
              {% endfor %}
              <a href="{% url 'customer:add_new_address' 'profile'%}" class="btn btn-secondary">add new</a>
            </td>

          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-12 d-flex flex-column gap-1">
      <h2 class="text-center">ACTIONS</h2>
      <button class="large-btn bg-green"><a href="{% url 'customer:change_password' %}" class="text-white">Change
          Password</a></button>
      <button class="large-btn bg-green"><a href="{% url 'customer:edit_profile' %}" class="text-white">Edit
          Profile</a></button>
      <button class="large-btn bg-green"><a href="{% url 'orders:wallet' %}" class="text-white">view Wallet</a></button>
    </div>
  </div>

  <div class="row mt-3">
    <div class="">
      <h2 class="text-center fs-montserrat">ORDERS</h2>

      <div class="row">
        {% for order in orders %}
        {% if not order.is_returned %}



        <div class="col-4 grid">
          <div class="card m-1">
            <div class="card-body">
              <h5 class="card-title">Order ID: {{ order.id }}</h5>
              <p class="card-text">Order Date: {{ order.date_ordered }}</p>
              <p class="card-text">Order Total: ${{ order.total_price }}</p>
              <p class="card-text">Delivery Status: {{ order.delivery_status }}</p>
              <p class="card-text">Payment Method: {{ order.payment_method }}</p>
              <p class="card-text">Customer: {{ order.customer }}</p>
              <p class="card-text">Payment Status: {{ order.payment_status }}</p>
              {% if order.payment_status != "Paid" and order.is_cancelled == False %}
              <p class="card-text text-danger">Order Status: Not Paid </p>
              <a href="{% url 'orders:change_payment_method' order.id %}" class="btn btn-success">Pay now</a>

              {% endif %}
              {% if order.is_cancelled %}
              <p class="card-text text-danger">Order Status: Cancelled </p>

              {% else %}
              <p class="card-text">Order Status: Not Cancelled </p>
              {% endif %}

              {% if order.total_discount > 0 %}

              <p>You Saved: ${{order.total_discount}}</p>
              {% endif %}

              <p class="card-text">View Invoice: <a href="{% url 'orders:order_details' order.id %}">Click Here</a></p>



              <div class="row d-flex">
                {% for product in order.order_items.all %}
                <div class="col-md-4 grid">
                  <img src="{{ product.product.images.first.image.url }}" alt="{{ product.product.name }}">
                  {{ product.product.name | truncatechars:20 }}
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% empty %}
        <p>No orders yet</p>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="pagination">
    <span class="step-links">
      {% if orders.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ orders.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ orders.number }} of {{ orders.paginator.num_pages }}.
      </span>

      {% if orders.has_next %}
      <a href="?page={{ orders.next_page_number }}">next</a>
      <a href="?page={{ orders.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>
<script>
  function areYouSure(deleteUrl) {
    console.log('clicked');
  }
</script>
{% endblock content %}

tech_mart/customer/templates/customer/verify_otp.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h2>Verify OTP</h2>
        <form method="post" action="">
          {% csrf_token %}
          <p>Enter the OTP sent to your phone number:</p>
          <input type="text" name="otp" required>
          <button type="submit" class="btn btn-primary">Verify OTP</button>
        </form>
      
        <button type="button" class="btn btn-primary"> <a href="{% url 'customer:resend_otp' id %}" class="text-white">Resend OTP</a> </button>
    
      </div>
    </div>
  </div>
{% endblock %}