tech_mart/adminUser/urls.py
from django.urls import path
from . import views
app_name='adminUser'
urlpatterns=[
    path("",views.adminDashboard,name='users'),
    path("register",views.adminRegistration,name='adminregistration'),
    path('toggle/customer/<int:customer_id>/', views.toggle_customer_status, name='toggle_customer_status'),
    path('create/category/', views.create_category, name='create_category'),
    path('create/product/', views.create_product12, name='create_product'),
    path('edit/category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete/category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('edit/product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('error/',views.error_view,name='error'),
    path('users/',views.user_management,name='dashboard'),
    path('products/',views.product_management,name='products'),
    path('categories/',views.category_management,name='categories'),
    path('orders/',views.order_management,name='orders'),
    path('edit_order/<int:order_id>/',views.edit_order,name='edit_order'),
    path('sales_report/',views.sales_report,name='sales_report'),
    path('coupons/',views.coupon_management,name='coupons'),
    path('create/coupon/',views.create_coupon,name='create_coupon'),
    path('edit/coupon/<int:coupon_id>/',views.edit_coupon,name='edit_coupon'),
    path('delete/coupon/<int:coupon_id>/',views.delete_coupon,name='delete_coupon'),
   
]

tech_mart/cartapp/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('',views.cart_view,name='view_cart'),
    path('add/<str:slug>/',views.add_cart,name='add_cart'),
    path('remove/<str:slug>/',views.remove_item,name='remove_from_cart'),
    path('remove_all/<str:slug>/',views.remove_all_item,name='remove_all_from_cart'),
    path('add_to_wishlist/<str:slug>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<str:slug>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('wishlist/',views.whishlist,name='wishlist'),
    path('remove_coupon/',views.remove_coupon,name='remove_coupon'),



]

tech_mart/customer/urls.py
from django.urls import path
from . import views
#imports for forgotten password
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name='customer'
urlpatterns=[
    path('',views.registerView,name='register'),
    path('otp/<int:id>', views.verifyOtp, name='otp'),
    path("resend_otp/<int:id>",views.resendOtp,name='resend_otp'),    
    path("login/",views.login_view,name='login'),
    path("logout/",views.logout_view,name='logout'),
    path("profile/",views.profile_view,name='profile'),
    path("change_password/",views.change_password_view,name='change_password'),
    path("edit_profile/",views.edit_profile_view,name='edit_profile'),
    path("add_new_address/<str:source>",views.add_new_address,name='add_new_address'),
    path("edit_address/<int:id>",views.edit_address,name='edit_address'),
    path("delete_address/<int:id>",views.delete_address,name='delete_address'),
    path("check_username/",views.check_username,name='check_username'),
    path('validate_password/',views.validate_passwords_view,name='validate_passwords'),
    path('test_register/',views.test_register,name='test_register'),
    path('create_referral_link/',views.create_referral_link,name='create_referral_link'),
    

]

tech_mart/orders/urls.py
from django.urls import path
from. import views
app_name = 'orders'
urlpatterns = [
  
    path('place_order/',views.checkout,name='place_order'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel'),
    path('order_details/<int:id>',views.order_details,name='order_details'),
    path('payment_success/<str:id>',views.payment_success,name='payment_success'),
    path('payment_failed/<str:id>',views.payment_failed,name='payment_failed'),
    path('return_order/<int:id>',views.return_order,name='return_order'),
    path('wallet/',views.view_wallet,name='wallet'),
    path('chage_payment/<int:order_id>',views.change_payment_method,name='change_payment_method'),
  
  
    
]

tech_mart/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("product/<str:slug>", views.ProductDetail.as_view(), name="detail"),
    path("category1/", views.ShopList.as_view(), name="shop"),
    path('category/', views.allProdCat, name='allProdCat-old'),
    path('category/<slug:c_slug>/', views.allProdCat, name='by_category'),
    path('filter/', views.filter_product_list, name='allProdCat'),
     path('review/<int:pk>/edit/', views.edit_review, name='edit_review'),
]

tech_mart/tech_mart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("shop.urls")),
    path("accounts/",include("customer.urls")),
    path("cadmin/",include("adminUser.urls")),
    path("cart/",include("cartapp.urls")),
    path("orders/",include("orders.urls")),
    path("reset",include("passwordreset.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_mart/shop/forms.py
import os
from django import forms
from .models import Product, Category, ProductImage, Brand, Review


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ["slug", "created", "updated"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "image": forms.FileInput(attrs={"class": "form-control"}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["slug"]
        widgets = {
            "name": forms.TextInput(attrs={}),
            "brand": forms.Select(attrs={"class": "fs-poppins   w-100 p-2"}),
            "description": forms.Textarea(attrs={"class": "input-data textarea"}),
            "label": forms.Select(attrs={"class": "fs-poppins   w-100 p-2"}),
            "price": forms.NumberInput(attrs={}),
            "discount": forms.NumberInput(attrs={}),
            "category": forms.Select(attrs={"class": "fs-poppins  w-100 p-2"}),
            "stock": forms.NumberInput(attrs={}),
            "available": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

    def clean_discount(self):
        discount = self.cleaned_data.get("discount")
        if discount > 100 or discount < 0:
            raise forms.ValidationError("Discount must be between 0 and 100")
        return discount


class ProductImageForm(forms.ModelForm):
    images = forms.FileField(
        widget=forms.TextInput(
            attrs={
                "name": "images",
                "type": "File",
                "class": "form-control",
                "multiple": "True",
            }
        ),
        label="",
        required=False,
    )

    def clean_images(self):
        files =  self.cleaned_data.getlist("images")
        images = self.cleaned_data.get("images")

        for image in images:
            # Check for valid image format using a reliable list of extensions
            valid_extensions = ['jpg', 'jpeg', 'png', 'gif', 'bmp', '.webp']
            extension = os.path.splitext(image.name)[1].lower()
            print(extension)
            if extension not in valid_extensions:
                raise forms.ValidationError("Only image files allowed.")

        return images

    class Meta:
        model = ProductImage
        fields = ["images"]


class ProductFilterForm(forms.Form):
    price_min = forms.DecimalField(
        required=False, widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    price_max = forms.DecimalField(
        required=False, widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    brand = forms.ModelChoiceField(
        queryset=Brand.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={"class": "fs-poppins bg-black text-white rounded-pill w-100 p-2"}
        ),
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={"class": "fs-poppins bg-black text-white rounded-pill w-100 p-2"}
        ),
    )


class ReviewForm(forms.ModelForm):

    class Meta:
        RATING_CHOICES = [
            (0, "0 Stars"),
            (1, "1 Star"),
            (2, "2 Stars"),
            (3, "3 Stars"),
            (4, "4 Stars"),
            (5, "5 Stars"),
        ]
        model = Review
        fields = ["rating", "message"]
        widgets = {
            "rating": forms.Select(choices=RATING_CHOICES),
            "message": forms.Textarea(
                attrs={
                    "class": "input-data textarea fs-poppins form-control border  w-100 p-3",
                },
            ),
        }

tech_mart/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import Product, Category, ProductImage, Brand, Review
from .forms import ProductFilterForm, ReviewForm
from orders.models import Order, OrderItem
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class ProductList(ListView):
    model = Product
    context_object_name = "products"
    template_name = "shop/shop.html"
    paginate_by = 12  # Number of products per page


class ProductDetail(DetailView):
    model = Product
    template_name = "shop/product.html"
    context_object_name = "product"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the product's category
        product_category = self.object.category
        review_form = ReviewForm()
        can_add_review = False

        # Get other products of the same category (excluding the current product)
        related_products = Product.objects.filter(category=product_category).exclude(
            pk=self.object.pk
        )
        if self.request.user.is_authenticated:

            has_purchased = OrderItem.objects.filter(
                product=self.object,
                order__customer=self.request.user,
                order__delivery_status="Delivered",
            ).exists()

            has_left_a_review = Review.objects.filter(
                product=self.object, customer=self.request.user
            ).exists()
            can_add_review = has_purchased and not has_left_a_review
            context["has_purchased"] = has_purchased
            context["has_left_a_review"] = has_left_a_review

        context["related_products"] = related_products
        context["review_form"] = review_form
        context["can_add_review"] = can_add_review

        return context

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            # Save the review to the database with the current user
            review = review_form.save(commit=False)
            review.customer = request.user
            review.product = product
            review.save()

            # Redirect back to the product detail page after submission
            messages.success(request, "Review submitted successfully")
            review_form = ReviewForm()
            return redirect("shop:detail", slug=product.slug)
        else:
            messages.error(request, f"Error submitting review{review_form.errors}")
            print(review_form.errors)
            print(review_form)

        # If the form is not valid, re-render the product detail page with the form and errors
        return render(
            request,
            self.template_name,
            {"product": product, "review_form": review_form},
        )


def home(request):
    return render(request, "base.html")


class ShopList(ListView):
    model = Product
    context_object_name = "products"
    template_name = "shop/category.html"


from django.core.paginator import Paginator, EmptyPage, InvalidPage


def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None

    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    products = products_list

    return render(
        request, "shop/category.html", {"category": c_page, "products": products}
    )


def filter_product_list(request):
    form = ProductFilterForm(request.GET)
    products = Product.objects.all()

    if form.is_valid():
        if form.cleaned_data.get("price_min"):
            products = products.filter(price__gte=form.cleaned_data["price_min"])
        if form.cleaned_data.get("price_max"):
            products = products.filter(price__lte=form.cleaned_data["price_max"])
        if form.cleaned_data.get("brand"):
            products = products.filter(brand=form.cleaned_data["brand"])
        if form.cleaned_data.get("category"):
            products = products.filter(category=form.cleaned_data["category"])
        search_query = request.GET.get("search", "")
        if search_query:
            products = products.filter(name__icontains=search_query)

    paginator = Paginator(products, 10)  # Show 10 products per page
    page = request.GET.get("page")
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render(request, "shop/category.html", {"form": form, "products": products})


@login_required
def edit_review(request, pk):
    review = get_object_or_404(Review, pk=pk, customer=request.user)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("shop:detail", slug=review.product.slug)
    else:
        review_form = ReviewForm(instance=review)

    context = {
        "review_form": review_form,
        "review": review,
    }
    return render(request, "shop/edit_review.html", context)

tech_mart/templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />

    <!-- Icon -->
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
    />
    <!-- icon -->

    <!-- Google fonts End -->

    <!-- custon style Sheet & JavaScript -->
    <link rel="stylesheet" href="shop.css" />
    <link rel="stylesheet" href="index.css" />
    <link rel="stylesheet" href="about.css">
    <script src="index.js" defer></script>
    <script src="shop.js" defer></script>
    <!-- custon style Sheet & JavaScript -->
    <title>Ecommerce Website</title>
  </head>
  <body class="home">
    <header class="primary-header container flex">
      <div class="header-inner-one flex">
        <div class="logo">
          <img src="/image/logo.png" alt="" />
        </div>
        <button
          class="mobile-close-btn"
          data-visible="false"
          aria-controls="primary-navigation"
        >
          <i class="uil uil-times-circle"></i>
        </button>
        <nav>
          <ul
            id="primary-navigation"
            data-visible="false"
            class="primary-navigation flex"
          >
            <li>
              <a class="fs-100 fs-montserrat bold-500" href="/index.html"
                >Home</a
              >
            </li>
            <li>
              <a class="fs-100 fs-montserrat bold-500" href="/shop.html">Shop</a>
            </li>
            <li>
              <a class="active fs-100 fs-montserrat bold-500" href="/about.html"
                >About Us</a
              >
            </li>
            <li>
              <a class="fs-100 fs-montserrat bold-500" href="/blog.html">Blog</a>
            </li>
            <li>
              <a class="fs-100 fs-montserrat bold-500" href="/contactus.html"
                >Contact Us</a
              >
            </li>
          </ul>
        </nav>
      </div>

      <div class="header-login flex">
        <p class="fs-100 fs-montserrat bold-500">login</p>
        <i class="uil uil-search"></i>
        <i
          id="cart-box"
          aria-controls="cart-icon"
          class="uil uil-shopping-bag"
        ></i>

        <!-- =================1111111111================== -->
        <div id="cart-icon" data-visible="false" class="cart-icon">
          <div class="shopping flex">
            <p>Shopping Basket</p>
            <i id="cross-btn" class="uil uil-times"></i>
          </div>
          <div class="cart bold-800 flex">
            <i class="uil uil-shopping-cart-alt"></i>
            <p>Cart Is Empty</p>

            <!-- ================================================== -->

            <!-- ================================================== -->
          </div>
        </div>
      </div>
      <div class="mobile-open-btn"><i class="uil uil-align-right"></i></div>
    </header>



    <!-- ===================Shop Feature Section============================ -->

    <section class="shop-feature bg-gray grid">
      <div>
        <p class="fs-montserrat text-black">
          Home <span aria-hidden="true" class="margin">></span> About Us
        </p>
      </div>
      <h2 class="fs-poppins fs-300 bold-700">About Us</h2>
    </section>

    <!-- ========================About Section========================== -->

   <section class="about-section grid">
       <div>
           <img src="/image/about-us.png" alt="">
       </div>
       <div class="about-info">
           <h3 class="fs-poppins fs-200 text-red">Welcome To Digital Ecommerce</h3>
           <h1 class="fs-poppins fs-500 text-black">Who We Are?</h1>
           <p class="fs-montserrat fs-100">When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray<br><br>

            gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me .<br><br>
            when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence .</p>
            <div class="about-btn">
                <button class="large-btn bg-red text-white fs-poppins fs-50">Shop By Category</button>
              </div>
       </div>
   </section>




    <!-- ========================About Section========================== -->




     <!-- =====================Footer Section================ -->

     <footer>

        <!-- =============Brands================= -->
        <section class="brands grid">
          <div>
         <img src="/image/br-1.png" alt="">
        </div>
          <div>
         <img src="/image/br-2.png" alt="">
        </div>
          <div>
         <img src="/image/br-3.png" alt="">
        </div>
          <div>
         <img src="/image/br-4.png" alt="">
        </div>
          <div>
         <img src="/image/br-5.png" alt="">
        </div>
        </section>
    
    <!-- =============Footer Menu=================== -->
     <section class="footer grid">
         <div class="footer-logo grid">
           <img src="/image/logo.png" alt="">
           <p class="fs-montserrat fs-200">There are many variations passages of Lorem Ipsum available, but the majority have</p>
           <div class="social-media flex">
            <i class="uil uil-facebook-f"></i>
            <i class="uil uil-instagram"></i>
            <i class="uil uil-linkedin"></i>
            <i class="uil uil-twitter"></i>
           </div>
         </div>
        
          <div class="footer-menu grid">
            <h3 class="fs-poppins fs-200 bold-800">Quick Links</h3>
            <ul>
              <li><a class="fs-montserrat text-black fs-200" href="#">Home</a></li>
              <li><a class="fs-montserrat text-black fs-200" href="#">About</a></li>
              <li><a class="fs-montserrat text-black fs-200" href="#">Shop</a></li>
              <li><a class="fs-montserrat text-black fs-200" href="#">Contact</a></li>
            </ul>
          </div>
    
          <div class="contact grid">
    
          <h3 class="fs-poppins fs-200 bold-800">Contact</h3>
          <p class="fs-montserrat">+99 (0) 101 0000 888 Patricia C. Amedee 4401 Waldeck Street Grapevine Nashville, Tx 76051</p>
         </div>
    
         <div class="emails grid">
           <h3 class="fs-poppins fs-200 bold-800">Subscribe To Our Email</h3>
           <p class="updates fs-poppins fs-300 bold-800">For Latest News & Updates</p>
           <div class="inputField flex bg-gray">
           <input type="email" placeholder="Enter Your Email" class="fs-montserrat bg-gray" >
           <button class="bg-red text-white fs-poppins fs-50">Subscribe</button>
          </div>
         </div>
     </section>
    
     <section class="copyRight">
      <p class="c-font fs-montserrat fs-200">© 2022 eStore. All rights reserved.</p>
      <p class="fs-montserrat fs-100 text-align p-top">Privacy Policy . Term Condition</p>
     </section>
    
      </footer>
  </body>
</html>

tech_mart/templates/admin.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>ADMIN PANEL</h1>
    <div class="row">
        {% for user in users %}
        <div class="col-4">
            
            
            
            <div class="card border-success mb-3" >
                <div class="card-header">User</div>
                <div class="card-body">
                  <h4 class="card-title">{{user.username}}</h4>
                  <p class="card-text"><a href="{% url 'detail' user.id %}" class="btn btn-secondary ">open</a></p>
                </div>
        </div>
        
        
    </div>
    {% endfor %}
</div>
</div>


{% endblock content %}

tech_mart/templates/carousal.html
<!-- Any template file -->

<div id="carouselExampleDark" class="carousel carousel-dark slide pt-2">
    <div class="carousel-inner">
        {% for category in categories %}
        
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ category.image.url }}" class="d-block w-100 px-auto px-2" alt="{{ category.name }}">
                <div class="carousel-caption d-none d-md-block ">
                    <h2 class="text-white fw-bold">{{ category.name }}</h2>
                </div>
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

tech_mart/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-white mb-3">
  <div class="container-fluid">

    <a class="navbar-brand" href="#">

      <img src="{% static '/image/logo2.png' %}" alt="Logo" class="d-inline-block align-text-top logo">


    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse mr-3 " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-5">
        <li class="nav-item">
          <a class="nav-link active fs-100 fs-montserrat bold-500" aria-current="page"
            href="{% url 'shop:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fs-100 fs-montserrat bold-500" href="{% url 'shop:allProdCat' %}">Shop</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link fs-100 fs-montserrat bold-500 flex"
            href="{% url 'customer:profile' %}">{{user.username}}|Profile</a>
          {% if request.user.is_superuser %}

        <li>
          <div class="dropdown">
            <button class="btn  dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"
              style="border-radius: 0%;">
              Dashboard
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'adminUser:dashboard' %}">Users</a></li>
              <li><a class="dropdown-item" href="{% url 'adminUser:products' %}">Products</a></li>
              <li><a class="dropdown-item" href="{% url 'adminUser:categories' %}">Categories</a></li>
              <li><a class="dropdown-item" href="{% url 'adminUser:orders' %}">Orders</a></li>
              <li><a class="dropdown-item" href="{% url 'adminUser:coupons' %}">Coupons</a></li>
              <li><a class="dropdown-item" href="{% url 'adminUser:sales_report' %}">Sales Report</a></li>
            </ul>
          </div>

        </li>
        {% endif %}
        {% endif %}


      </ul>
      <div class="header-login flex justify-space-between gap-5">

        {% if request.user.is_authenticated %}
        <ul>
          <span class="nav-item">
            <a class="nav-link active fs-100 fs-montserrat bold-500" href="{% url 'customer:logout' %}"> logout
              <span class="visually-hidden">(current)</span>
            </a>
          </span>
          {% else %}
          <span class="nav-item">
            <a class="nav-link active fs-100 fs-montserrat bold-500" href="{% url 'customer:login' %}">login
              <span class="visually-hidden">(current)</span>
            </a>
          </span>
          {% endif %}
        </ul>
        <div class="flex  align-items-center">
          <a href="{% url 'cart:view_cart' %}" class="text-black">
            <div class="d-flex align-items-center"><i class="uil uil-shopping-bag "></i><sup
                class="bg-red text-white rounded-circle p-2">{{cart_count}}</sup></div>
          </a>
          <a href="{% url 'cart:wishlist' %}" class="text-black">
            <div class=""><a href="{% url 'cart:wishlist' %}" class="text-black">
                <div class="d-flex align-items-center fs-200"><i class="uil uil-heart-alt "></i>
              </a>

              <a  class="ms-2" href="{% url 'orders:wallet' %}"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"
                  id="wallet">
                  <g fill="none" fill-rule="evenodd" stroke="#200E32" stroke-linecap="round" stroke-linejoin="round"
                    stroke-width="1.5" transform="translate(2.5 3)">
                    <path
                      d="M19.1389383,11.3957621 L15.0906357,11.3957621 C13.6041923,11.3948508 12.399362,10.1909319 12.3984507,8.70448849 C12.3984507,7.21804511 13.6041923,6.01412622 15.0906357,6.01321486 L19.1389383,6.01321486">
                    </path>
                    <line x1="15.549" x2="15.237" y1="8.643" y2="8.643"></line>
                    <path
                      d="M5.24766462,1.52259158e-14 L13.8910914,1.52259158e-14 C16.7892458,1.52259158e-14 19.138756,2.34951014 19.138756,5.24766462 L19.138756,12.4246981 C19.138756,15.3228526 16.7892458,17.6723627 13.8910914,17.6723627 L5.24766462,17.6723627 C2.34951014,17.6723627 1.69176842e-15,15.3228526 1.69176842e-15,12.4246981 L1.69176842e-15,5.24766462 C1.69176842e-15,2.34951014 2.34951014,1.52259158e-14 5.24766462,1.52259158e-14 Z">
                    </path>
                    <line x1="4.536" x2="9.935" y1="4.538" y2="4.538"></line>
                  </g>
                </svg></a>
            




        </div>
      </div>
    </div>
</nav>