tech_mart/adminUser/urls.py
from django.urls import path
from . import views
app_name='adminUser'
urlpatterns=[
    path("",views.adminDashboard,name='users'),
    path("register",views.adminRegistration,name='adminregistration'),
    path('toggle/customer/<int:customer_id>/', views.toggle_customer_status, name='toggle_customer_status'),
    path('create/category/', views.create_category, name='create_category'),
    path('create/product/', views.create_product12, name='create_product'),
    path('edit/category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete/category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('edit/product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('error/',views.error_view,name='error'),
    path('users/',views.user_management,name='dashboard'),
    path('products/',views.product_management,name='products'),
    path('categories/',views.category_management,name='categories'),
    path('orders/',views.order_management,name='orders'),
    path('edit_order/<int:order_id>/',views.edit_order,name='edit_order'),
    path('sales_report/',views.sales_report,name='sales_report'),
    path('coupons/',views.coupon_management,name='coupons'),
    path('create/coupon/',views.create_coupon,name='create_coupon'),
    path('edit/coupon/<int:coupon_id>/',views.edit_coupon,name='edit_coupon'),
    path('delete/coupon/<int:coupon_id>/',views.delete_coupon,name='delete_coupon'),
   
]

tech_mart/orders/urls.py
from django.urls import path
from. import views
app_name = 'orders'
urlpatterns = [
  
    path('place_order/',views.checkout,name='place_order'),
    path('cancel_order/<int:id>',views.cancel_order,name='cancel'),
    path('order_details/<int:id>',views.order_details,name='order_details'),
    path('payment_success/<str:id>',views.payment_success,name='payment_success'),
    path('payment_failed/<str:id>',views.payment_failed,name='payment_failed'),
    path('return_order/<int:id>',views.return_order,name='return_order'),
    path('wallet/',views.view_wallet,name='wallet'),
    path('chage_payment/<int:order_id>',views.change_payment_method,name='change_payment_method'),
  
  
    
]

tech_mart/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("product/<str:slug>", views.ProductDetail.as_view(), name="detail"),
    path("category1/", views.ShopList.as_view(), name="shop"),
    path('category/', views.allProdCat, name='allProdCat-old'),
    path('category/<slug:c_slug>/', views.allProdCat, name='by_category'),
    path('filter/', views.filter_product_list, name='allProdCat'),
     path('review/<int:pk>/edit/', views.edit_review, name='edit_review'),
]

tech_mart/tech_mart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("shop.urls")),
    path("accounts/",include("customer.urls")),
    path("cadmin/",include("adminUser.urls")),
    path("cart/",include("cartapp.urls")),
    path("orders/",include("orders.urls")),
    path("reset",include("passwordreset.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_mart/orders/models.py
"""
Order and OrderItem models for ecommerce site.

Order tracks order details like customer, status, payment info. 
OrderItem tracks line items with product and quantity.
"""

from django.db import models
from customer.models import Customer
from cartapp.models import Cart
from shop.models import validate_non_empty
from django.core.validators import MinLengthValidator,MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

# Create your models here.
class Order(models.Model):
    PAYMENT_CHOICES = (
        ("Razorpay", "Razorpay"),
        ("Cash On Delivery", "Cash On Delivery"),
        ("Wallet", "Wallet"),
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,related_name='orders')
    payment_status = models.CharField(
        max_length=20,
        choices=[("Pending", "Pending"), ("Paid", "Paid"),("Failed","Failed")],
        default="Pending",
    )
    delivery_status = models.CharField(
        max_length=20,
        choices=[
            ("Pending", "Pending"),
            ("Shipped", "Shipped"),
            ("Delivered", "Delivered"),
            ("Cancelled", "Cancelled"),
        ],
        default="Pending",
    )
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    payment_method = models.CharField(
        max_length=100, choices=PAYMENT_CHOICES, default="Cash On Delivery"
    )
    delivery_address = models.CharField(max_length=250, null=True,validators=[MinLengthValidator(10, "Delivery address must be at least 10 characters"),validate_non_empty])
    is_cancelled = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=100, decimal_places=2, default=0)
    total_discount = models.DecimalField(max_digits=100, decimal_places=2, default=0)
    razorpay_payment_id = models.CharField(max_length=100, null=True,blank = True)
    razorpay_order_id = models.CharField(max_length=100, null=True,blank = True)
    razorpay_payment_signature = models.CharField(max_length=100, null=True,blank = True)
    is_returned = models.BooleanField(default=False)
    delivery_date = models.DateTimeField(null=True,blank = True)
    

    def __str__(self):
        return f"{self.customer.username}'s Order #{self.id}"
    class Meta:
        ordering = ['-date_ordered','is_cancelled']
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,related_name='order_items')
    product = models.ForeignKey("shop.Product", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

    def total_per_item(self):
        if self.product.discount:
            total = self.product.price * self.quantity - (
                self.product.price * self.quantity * self.product.discount / 100
            )
        else:
            total = self.product.price * self.quantity
        return round(total, 2)
    

tech_mart/adminUser/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AdminCreationForm, OrdersForm
from django.contrib import messages
from shop.forms import ProductForm, CategoryForm, ProductImageForm
from customer.models import Customer
from shop.models import Product, Category, ProductImage
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.cache import never_cache
from django.views import View
from orders.models import Order, OrderItem
from django.utils import timezone
from django.db.models import Sum, Count
from django.db.models.functions import TruncDate
from django.db.models import F
from cartapp.models import Coupons, UserCoupons
from cartapp.forms import CouponForm
from django.shortcuts import render
from django.db.models import Sum, Count, Case, When, IntegerField
from django.db.models.functions import ExtractYear, ExtractMonth, ExtractDay, TruncDate
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from datetime import date, datetime, timedelta
import csv
from reportlab.lib.pagesizes import letter
from django.http import HttpResponse, JsonResponse
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph
from reportlab.lib.units import inch
from reportlab.platypus import Spacer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@never_cache
def adminRegistration(request):
    if request.user.is_authenticated:
        return redirect("customer:dashboard")
    form = AdminCreationForm()
    if request.method == "POST":
        form = AdminCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "admin user created successfully!!")
            return redirect("customer:login")
        else:
            messages.error(request, form.errors)
            return redirect("adminUser:adminregistration")
    return render(request, "adminUser/register.html", {"form": form})


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def adminDashboard(request):
    users = Customer.objects.all()
    products = Product.objects.all()
    categories = Category.objects.all()
    orders = Order.objects.all()

    context = {
        "users": users,
        "products": products,
        "categories": categories,
        "orders": orders,
    }

    return render(request, "adminUser/dashboard.html", context)


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def toggle_customer_status(request, customer_id):
    customer = get_object_or_404(Customer, id=customer_id)

    if customer.is_active:
        customer.is_active = False
        customer.save()
        messages.success(request, "Customer deactivated successfully.")
    else:
        customer.is_active = True
        customer.save()
        messages.success(request, "Customer activated successfully.")
    return redirect("adminUser:dashboard")


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def create_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Category created successfully.")
            return redirect("adminUser:categories")
        else:
            messages.error(request, form.errors)
    else:
        form = CategoryForm()

    return render(request, "adminUser/create_category.html", {"form": form})


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def edit_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "updated successfully")
            return redirect("adminUser:categories")
    else:
        form = CategoryForm(instance=category)
        messages.error(request, form.errors)

    return render(request, "adminUser/edit.html", {"form": form, "model": "Category"})


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    productform = ProductForm(instance=product)
    imageform = ProductImageForm()

    if request.method == "POST":
        productform = ProductForm(request.POST, request.FILES, instance=product)

        if productform.is_valid():
            product = productform.save(commit=False)
            product.save()

            # If images are provided, update them; otherwise, keep the old ones
            if request.FILES.getlist("images"):
                # check if files are images
                for file in request.FILES.getlist("images"):
                    if file.content_type not in ["image/jpeg", "image/png", "image/gif", "image/svg+xml", "image/webp"]:
                        messages.error(request, "Only images are allowed.")
                        return render(request, "adminUser/create_new.html", {"p_form": productform, "i_form": imageform, "operation": "update", "product": product})
                # Delete old images if needed
                product.images.all().delete()

                # Create new images
                for file in request.FILES.getlist("images"):
                    ProductImage.objects.create(product=product, image=file)

            messages.success(request, "Product updated successfully")
            return redirect("adminUser:products")
        else:
            messages.error(request, productform.errors)

    context = {
        "p_form": productform,
        "i_form": imageform,
        "operation": "update",
        "product": product,
    }
    return render(request, "adminUser/create_new.html", context)


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def user_management(request):
    users_list = Customer.objects.all()
    paginator = Paginator(users_list, 10)  # Show 10 users per page

    page = request.GET.get("page")
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        users = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        users = paginator.page(paginator.num_pages)

    return render(request, "adminUser/user_management.html", {"users": users})


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def product_management(request):
    products_list = Product.objects.all()
    paginator = Paginator(products_list, 10)  # Show 10 products per page

    page = request.GET.get("page")
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render(request, "adminUser/product_management.html", {"products": products})


@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    try:
        category.delete()
        messages.success(request, "Deleted category successfully.")
    except Exception as e:
        messages.error(request, f"Error deleting category: {e}")

    return redirect("adminUser:categories")


@user_passes_test(lambda u: u.is_superuser, login_url="error")
@never_cache
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        product.delete()
        messages.success(request, "Deleted product successfully.")
    except Exception as e:
        messages.error(request, f"Error deleting product: {e}")

    return redirect("adminUser:products")


def error_view(request):
    messages.error(request, "only admims are authorised for this function")
    return redirect("shop:home")


@user_passes_test(lambda u: u.is_superuser, login_url="error")
@never_cache
def create_product12(request):
    productform = ProductForm()
    imageform = ProductImageForm()

    if request.method == "POST":

        files = request.FILES.getlist("images")
        for file in files:
            if file.content_type not in ["image/jpeg", "image/png", "image/gif", "image/svg+xml", "image/webp"]:
                        messages.error(request, "Only images are allowed.")
                        return render(request, "adminUser/create_new.html", {"p_form": productform, "i_form": imageform, "operation": "create"})
                        
        

        productform = ProductForm(request.POST, request.FILES)
        if productform.is_valid():
            product = productform.save(commit=False)

            product.save()
            messages.success(request, "Product created successfully")

            for file in files:

                ProductImage.objects.create(product=product, image=file)
                

            return redirect("adminUser:products")
        else:
            messages.error(request, productform.errors)

    context = {"p_form": productform, "i_form": imageform, "operation": "create"}
    return render(request, "adminUser/create_new.html", context)

@user_passes_test(lambda u: u.is_superuser, login_url="adminUser:error")
@never_cache
def category_management(request):
    categories = Category.objects.all()
    return render(
        request, "adminUser/category_management.html", {"categories": categories}
    )

tech_mart/adminUser/templates/adminUser/coupons_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h2 class='d-flex justify-content-between'>
            <button class="btn btn-primary w-100 mb-2" >
                Coupons
                <button class="btn btn-success w-25 mb-2" type="button" ><a href="{% url 'adminUser:create_coupon' %}" class="text-white">Create New <i><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" id="plus"><g transform="translate(936.994 -962.858)"><circle cx="-928.994" cy="970.858" r="7" fill="#e9eded" color="#000" overflow="visible" style="marker:none"></circle><path fill="#25b39e" fill-rule="evenodd" stroke="#25b39e" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m-932.488 970.864 6.987-.011m-3.499-3.488.011 6.987"></path></g></svg></i></a>
            </button></button>
        </h2>
        <div >
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Code</th>
                        <th>Discount</th>
                        <th>Valid From</th>
                        <th>Valid To</th>
                        <th>Is Expired</th>
                        <th>Minimum amout</th>
                        <th>description</th>
                        <th>Actions</th>
                            
                     
                    
                    </tr>
                </thead>
                <tbody>
                   {% for coupon in coupons %}
                   <tr>
                    <td>{{coupon.id}}</td>
                    <td>{{coupon.coupon_code}}</td>
                    <td>{{coupon.discount}}</td>
                    <td>{{coupon.valid_from}}</td>
                    <td>{{coupon.valid_to}}</td>
                    <td>{{coupon.is_expired}}</td>
                    <td>{{coupon.minimum_amount}}</td>
                    <td>{{coupon.description}}</td>
                    <td><a href="{% url 'adminUser:edit_coupon' coupon.id %}" class="btn btn-warning"><i
                        class="fa-solid fa-pen-to-square"></i></a></td>
                    <td><a href="{% url 'adminUser:delete_coupon' coupon.id %}" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></a></td>
                </tbody>
                
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

tech_mart/adminUser/templates/adminUser/create_category.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2>Create new</h2>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

  


                <button type="submit" class="btn btn-success mt-2">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

tech_mart/adminUser/templates/adminUser/dashboard.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h2>
            <button class="btn btn-primary w-100 mb-2" type="button" data-toggle="collapse" data-target="#usersTable" aria-expanded="true" aria-controls="usersTable">
                Users
            </button>
        </h2>
        <div class="collapse " id="usersTable">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>is_active</th>
                        <th>Deactivate/Activate</th>
                        <th>Verified</th>
                        
                        

                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.is_active }}</td>
                            <td>
                                <form method="post" action="{% url 'adminUser:toggle_customer_status' user.id %}">
                                    {% csrf_token %}
                                    <input type="checkbox" name="confirm_deactivation">
                                    <button type="submit" class="btn btn-warning">
                                        {% if user.is_active %}
                                            Deactivate
                                        {% else %}
                                            Activate
                                        {% endif %}
                                    </button>
                                </form>
                            </td>
                            <td>{{ user.is_verified }}</td>
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
        
        <button class="btn btn-primary w-100 mb-2" type="button" data-toggle="collapse" data-target="#ordersTable" aria-expanded="true" aria-controls="usersTable">
            Orders
        </button>
        <div class="collapse " id="ordersTable">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Date</th>
                        <th>Completed</th>
                        <th>Payment</th>
                        <th>Products</th>
                        <th>Total</th>
                        <th>User</th>
                        </tr>
                        {% for order in orders %}
                        <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.date_ordered }}</td>
                        <td>{{ order.complete }}</td>
                        <td>{{order.payment_method}}</td>
                        <td>
                            {% for product in order.orderitem_set.all %}
                            {{ product.product.name }} <br>
                        {% endfor %}
                           <td>{{order.total}}</td>
                           <td>{{order.customer}}</td>
                        </tr>
                    
                        {% endfor %}
                </tbody>
                
            </table>
        </div>

        <h2 class='d-flex justify-content-between'>
            <button class="btn btn-primary w-100 mb-2" type="button" data-toggle="collapse" data-target="#productsTable" aria-expanded="true" aria-controls="productsTable">
                Products
                <button class="btn btn-success w-25 mb-2" type="button" ><a href="{% url 'adminUser:create_product' %}" class="text-white">Create New <i><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" id="plus"><g transform="translate(936.994 -962.858)"><circle cx="-928.994" cy="970.858" r="7" fill="#e9eded" color="#000" overflow="visible" style="marker:none"></circle><path fill="#25b39e" fill-rule="evenodd" stroke="#25b39e" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m-932.488 970.864 6.987-.011m-3.499-3.488.011 6.987"></path></g></svg></i></a>
            </button></button>
        </h2>
        <div class="collapse " id="productsTable">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Stock</th>
                        <th>Edit</th>
                        <th>Delete</th>
                     
                    
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                            <td>{{ product.id }}</td>
                            <td>{{ product.name }}</td>
                            <td>₹{{ product.price_after_discount }}</td>
                            <td>{{ product.category.name }}</td>
                            <td>{{ product.stock }}</td>
                            <td><a href="{% url 'adminUser:edit_product' product.id %}" class="btn btn-warning">edit</a></td>
                            <td><a href="{% url 'adminUser:delete_product' product.id %}" class="btn btn-danger">delete</a></td>
                            
                          
                        </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>

        <h2 class="d-flex ">
            <button class="btn btn-primary w-100 mb-2" type="button" data-toggle="collapse" data-target="#categoriesTable" aria-expanded="true" aria-controls="categoriesTable">
                Categories
                <button class="btn btn-success w-25 mb-2 " type="button" ><a href="{% url 'adminUser:create_category' %}" class="text-white">Create New <i><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" id="plus"><g transform="translate(936.994 -962.858)"><circle cx="-928.994" cy="970.858" r="7" fill="#e9eded" color="#000" overflow="visible" style="marker:none"></circle><path fill="#25b39e" fill-rule="evenodd" stroke="#25b39e" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m-932.488 970.864 6.987-.011m-3.499-3.488.011 6.987"></path></g></svg></i></a></button>
            </button>
           
        </h2>
        <div class="collapse " id="categoriesTable">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Edit</th>
                        <th>Delete</th>


                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                        <tr>
                            <td>{{ category.id }}</td>
                            <td>{{ category.name }}</td>
                            <td><a href="{% url 'adminUser:edit_category' category.id %}" class="btn btn-warning">edit</a></td>
                            <td><a href="{% url 'adminUser:delete_category' category.id %}" class="btn btn-danger">delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
                
            </table>
            </table>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

tech_mart/adminUser/templates/adminUser/deactivate_customer.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
           <h2>Deactivate Customer</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Deactivate Customer</button>
        <a href="{% url 'adminUser:dashboard' %}">Cancel</a>
    </form>
        </div>
    </div>
</div>
{% endblock content %}

tech_mart/adminUser/templates/adminUser/order_management.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="">
          <h2 class="text-center fs-montserrat">ORDERS</h2>
  
          <div class="row">
            {% for order in orders %}
              <div class="col-4 grid">
                <div class="card m-1">
                  <div class="card-body">
                    <h5 class="card-title">Order ID: {{ order.id }}</h5>
                    <p class="card-text">Order Date: {{ order.date_ordered }}</p>
                    <p class="card-text">Order Total: ${{ order.total_price }}</p>
                    <p class="card-text">Delivery Status: {{ order.delivery_status }}</p>
                    <p class="card-text">Payment Method: {{ order.payment_method }}</p>
                    <p class="card-text">Customer: {{ order.customer }}</p>
                    <p class="card-text">Payment Status: {{ order.payment_status }}</p>
                    <p class="card-text">Is Returned: {{ order.is_returned }}</p>
                    
                    {% if order.is_cancelled %}
                    <p class="card-text text-danger">Order Status: Cancelled </p>
                    {% else %}
                    <p class="card-text">Order Status: Not Cancelled </p>
                    {% endif %}
  
                    <p class="card-text">Detail View: <a href="{% url 'orders:order_details' order.id %}">Click Here</a></p>
                    <p class="card-text">Edit: <a href="{% url 'adminUser:edit_order' order.id %}">Click Here</a></p>
                    
                    <div class="row d-flex">
                      {% for product in order.order_items.all %}
                        <div class="col-md-4 grid">
                          <img src="{{ product.product.images.first.image.url }}" alt="{{ product.product.name }}">
                          {{ product.product.name | truncatechars:20 }}
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            {% empty %}
              <p>No orders yet</p>
            {% endfor %}
          </div>
        </div>
      </div>

    <!-- Pagination -->
    <div class="pagination">
        <span class="step-links">
            {% if orders.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ orders.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ orders.number }} of {{ orders.paginator.num_pages }}.
            </span>

            {% if orders.has_next %}
                <a href="?page={{ orders.next_page_number }}">next</a>
                <a href="?page={{ orders.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}